# -*- coding: utf-8 -*-
"""phishing_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7LjmQJ5t1ie-JfTrjuDA46HKb-Cwtby

#1. AI 점수

**1-1. 데이터 가져오기**
"""

!pip install transformers torch scikit-learn sentencepiece tqdm

from google.colab import files
uploaded = files.upload()

import pandas as pd

# CSV 파일 읽기
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

df = df.drop(columns=["구분", "출처"])

# 컬럼 분리
texts = (df["상황"] + " " + df["문장"]).tolist()
labels = df["라벨"].tolist()

"""**1-2. 데이터 자동증강**"""

!pip install nlpaug

import nlpaug.augmenter.word as naw
import pandas as pd
import random

aug_syn = naw.SynonymAug(aug_src='wordnet')  # 영어 기반이라 제한적

replace_dict = {
    # 기관/수사 관련
    "검찰": ["수사기관", "검찰청", "수사팀", "형사부", "사법기관"],
    "경찰": ["경찰청", "수사과", "사이버수사대", "수사관"],
    "수사": ["조사", "내사", "수사 진행", "조사 절차"],
    "담당": ["전담", "배정된", "책임", "관할"],

    # 금융/계좌
    "계좌": ["통장", "계정", "금융계좌", "거래계좌"],
    "송금": ["이체", "입금", "이체 처리", "자금 이동"],
    "입금": ["송금", "이체", "납부", "이체 완료"],
    "금액": ["금액대", "금액 정보", "거래 금액"],
    "결제": ["결제 처리", "승인", "거래 승인", "지불"],

    # 확인/조치
    "확인": ["검토", "점검", "확인 요청", "검증"],
    "점검": ["확인", "검토", "조사", "확인 절차"],
    "처리": ["진행", "조치", "진행 중", "처리 진행"],
    "조치": ["처리", "대응", "조정", "조치 진행"],

    # 연락/통보
    "연락": ["통보", "안내", "알림", "연락 요청"],
    "안내": ["공지", "통보", "고지", "알림"],
    "통보": ["안내", "고지", "연락", "전달"],

    # 긴급성 (피싱 핵심)
    "즉시": ["바로", "긴급히", "당장", "즉각"],
    "지금": ["현재", "즉시", "당장", "바로"],
    "긴급": ["중요", "비상", "긴급 상황", "즉시 대응"],
    "바로": ["즉시", "곧바로", "당장", "지금"],

    # 금전/피해 유도
    "피해": ["손해", "피해 발생", "금전 피해", "손실"],
    "환급": ["환불", "반환", "돌려받기", "환급 처리"],
    "보상": ["보상금", "배상", "보상 처리", "보상금 지급"],

    # 인증/보안
    "인증": ["확인", "검증", "본인확인", "인증 절차"],
    "비밀번호": ["비번", "암호", "접속 코드", "보안 코드"],
    "로그인": ["접속", "인증 접속", "로그인 시도", "접속 요청"],

    # 감정/압박 표현
    "필수": ["반드시", "필수사항", "의무", "필수 조건"],
    "필요": ["요구됨", "필수", "요청됨", "필요 사항"],
    "주의": ["경고", "주의사항", "보안 경고", "알림"],
}

import random

def augment_sentence(sentence, n=3):
    aug_list = []

    for _ in range(n):
        words = sentence.split()
        new_words = []

        for w in words:
            if w in replace_dict and random.random() < 0.7:
                new_words.append(random.choice(replace_dict[w]))
            else:
                new_words.append(w)

        new_sentence = " ".join(new_words)

        if new_sentence != sentence:
            aug_list.append(new_sentence)

    return aug_list

augmented_data = []

for row in data[1:]:
    label = row[4]
    sentence = row[3]

    augmented_data.append(row)

    if label == 1:
        aug_sentences = augment_sentence(sentence, n=3)
    else:
        aug_sentences = augment_sentence(sentence, n=4)

    for s in aug_sentences:
        new_row = row.copy()
        new_row[3] = s
        augmented_data.append(new_row)

columns = ["구분", "출처", "상황", "문장", "라벨"]
df_aug = pd.DataFrame(augmented_data, columns=columns)

df_aug.to_csv("augmented_phishing_dataset.csv",
              index=False,
              encoding="utf-8-sig")

df = df_aug.copy()

texts = (df["상황"] + " " + df["문장"]).tolist()
labels = df["라벨"].tolist()

"""**1-3. AI 학습**"""

from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts, labels, test_size=0.1
)

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification
from torch.optim import AdamW

tokenizer = BertTokenizer.from_pretrained("monologg/kobert")

class ScamDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = tokenizer(
            self.texts[idx],
            padding='max_length',
            truncation=True,
            max_length=128,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
            'labels': torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_loader = DataLoader(ScamDataset(train_texts, train_labels), batch_size=4, shuffle=True)
val_loader = DataLoader(ScamDataset(val_texts, val_labels), batch_size=4)

model = BertForSequenceClassification.from_pretrained(
    "monologg/kobert",
    num_labels=2
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = AdamW(model.parameters(), lr=2e-5)

from tqdm import tqdm

for epoch in range(10):   # 처음은 2로 충분
    model.train()
    total_loss = 0

    for batch in tqdm(train_loader):
        optimizer.zero_grad()

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        optimizer.step()

    #print(f"Epoch {epoch+1}, Loss: {total_loss}")

def predict(text):
    model.eval()

    encoding = tokenizer(
        text,
        return_tensors='pt',
        truncation=True,
        padding=True,
        max_length=128
    )

    input_ids = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)

    probs = torch.softmax(outputs.logits, dim=1)
    return probs[0][1].item()

def ai_score(text):
    return predict(text)

"""# 2. 키워드 점수"""

# 리스트 (기본 점수)
keywords_list = [
    "검찰", "경찰", "수사", "계좌", "동결", "인증번호",
    "앱 설치", "송금", "입금", "대포통장",
    "[Web]", "엄마", "아빠", "돈 보내",
    "결제되었습니다", "확인", "배송지 누락",
    "파일 설치", "영상 보내"
]

# 딕셔너리 (추가 가중치)
keywords_dict = {
    "검찰": 1,
    "경찰": 1,
    "인증번호": 1,
    "송금": 2,
    "돈 보내": 2,
    "파일 설치": 2,
    "앱 설치": 2
}

def keyword_score(text):
    score = 0

    # 리스트 점수 (+1)
    for word in keywords_list:
        if word in text:
            score += 1

    # 딕셔너리 추가 점수 (+가중치)
    for word, weight in keywords_dict.items():
        if word in text:
            score += weight

    # ✔ 최대 점수로 나눠서 0~1 정규화
    max_score = len(keywords_list) + sum(keywords_dict.values())
    return score / max_score

"""#3. 패턴점수"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

phishing_patterns = [
    # 기관/수사 사칭
    "계좌가 범죄에 연루되었습니다",
    "귀하의 계좌가 불법 거래에 사용되었습니다",
    "검찰청 수사관입니다",
    "경찰서 사이버수사팀입니다",
    "금융감독원에서 연락드렸습니다",
    "명의도용 사건으로 조사가 필요합니다",
    "대포통장 개설 혐의가 확인되었습니다",
    "본인 확인을 위해 개인정보가 필요합니다",

    # 인증/보안 정보 요구
    "인증번호를 알려주세요",
    "문자로 받은 인증번호를 불러주세요",
    "OTP 번호를 확인해야 합니다",
    "계좌 비밀번호 확인이 필요합니다",
    "보안카드 번호를 입력해주세요",

    # 송금/이체 유도
    "안전계좌로 돈을 이체해야 합니다",
    "피해 방지를 위해 임시 계좌로 송금하세요",
    "지금 바로 돈을 보내야 합니다",
    "환급 처리를 위해 계좌 입금이 필요합니다",
    "수수료를 먼저 입금해야 처리됩니다",

    # 가족/지인 사칭
    "엄마 나 휴대폰 고장났어",
    "아빠 나 지금 통화가 안 돼",
    "으로만 연락 가능해",
    "급하게 돈이 필요해",
    "친구 계좌로 대신 보내줘",
    "나중에 바로 갚을게 지금 먼저 보내줘",

    # 링크/앱 설치 유도
    "아래 링크를 눌러 확인해주세요",
    "보안 앱 설치가 필요합니다",
    "원격제어 앱을 설치해주세요",
    "파일을 다운로드해서 실행해주세요",
    "문자에 있는 주소로 접속해주세요",

    # 결제/배송 사칭
    "해외 결제가 승인되었습니다",
    "본인이 결제한 내역이 맞는지 확인해주세요",
    "배송지 정보가 누락되었습니다",
    "택배 반송 처리를 위해 주소 확인이 필요합니다",
    "환불 신청을 위해 계좌 정보를 입력해주세요",

    # 압박/협박
    "지금 처리하지 않으면 계좌가 정지됩니다",
    "불응 시 법적 조치가 진행됩니다",
    "오늘 안에 처리하지 않으면 불이익이 발생합니다",
    "본인 확인이 지연되면 수사가 진행됩니다"
]

vectorizer = TfidfVectorizer()
vectorizer.fit(phishing_patterns)

def pattern_score(text):
    text_vec = vectorizer.transform([text])
    pattern_vec = vectorizer.transform(phishing_patterns)

    similarity = cosine_similarity(text_vec, pattern_vec)

    return similarity.max()  # 가장 유사한 패턴 점수

"""#4. 민감도 점수"""

urgency_words = ["지금", "즉시", "바로", "당장", "급해"]

def urgency_score(text):
    count = 0
    for word in urgency_words:
        if word in text:
            count += 1

    score = count * 15
    return min(score, 100) / 100  # 0~1

"""#5. 맥락 점수"""

def context_score(text):
    score = 0

    # 기관 + 송금
    if ("검찰" in text or "경찰" in text) and ("송금" in text or "돈 보내" in text):
        score += 40

    # 인증번호 요구
    if "인증번호" in text:
        score += 30

    # 설치 요구
    if "설치" in text:
        score += 30

    return min(score, 100) / 100  # 0~1

"""#6. 최종 결합"""

import math

def sigmoid(x):
    return 1 / (1 + math.exp(-x))


def final_probability(text):
    K = keyword_score(text)
    P = pattern_score(text)
    AI = ai_score(text)
    U = urgency_score(text)
    C = context_score(text)

    z = -3 + 5*K + 5*P + 10*AI + 4*U + 5*C
    prob = sigmoid(z)

    return prob, {
        "K": K,
        "P": P,
        "AI": AI,
        "U": U,
        "C": C,
        "z": z
    }


def is_phishing_final(prob, K, P, AI, U, C):

    if prob < 0.75:
        return False, prob

    if AI < 0.4:
        return False, prob

    risk_signal = (P > 0.4) or (U > 0.5) or (K > 0.3)

    if not risk_signal:
        return False, prob

    return True, prob

prob, detail = final_probability(text)

label, prob = is_phishing_final(
    prob,
    detail["K"],
    detail["P"],
    detail["AI"],
    detail["U"],
    detail["C"]
)

def classify(prob):
    if prob >= 0.75:
        return "🚨 피싱 위험"
    elif prob >= 0.45:
        return "⚠️ 의심"
    else:
        return "✅ 정상"

test_cases = [
    "배고파",
    "검찰입니다 계좌 확인 필요 송금 하세요",
    "[Web]계좌 사기 수사관 배정됐습니다",
    "검찰입니다 계좌 확인 필요 송금 하세요"
]#이부분을 입력 받는 곳으로 만드는 것이 좋을 것 같다.

#예시

#while True:
#    t = input("\n입력 > ")

#    if t == "q":
#        print("종료합니다.")
#        break

#    prob, detail = final_probability(t)
#    label = classify(prob)

for t in test_cases:
    prob, detail = final_probability(t)

    label = classify(prob)

    # 출력 가능한 것들
    print("문장:", t)
    print(f"키워드(K): {detail['K']:.4f}")
    print(f"패턴(P): {detail['P']:.4f}")
    print(f"AI:       {detail['AI']:.4f}")
    print(f"긴급성(U): {detail['U']:.4f}")
    print(f"맥락(C):   {detail['C']:.4f}")
    print(f"z 값:     {detail['z']:.4f}")
    print(f"최종 확률: {round(prob * 100)}%")
    print(f"판정: {label}")
    print("-" * 50)